FROM ubuntu:22.04

RUN apt-get update
RUN apt-get --yes install curl git cmake build-essential ninja-build python3

RUN sh -c "cd /tmp;curl --silent --output avr-gcc-toolchain.tar.gz 'https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-3.7.0.1796-linux.any.x86_64.tar.gz'"
RUN sh -c "cd /tmp;tar xf avr-gcc-toolchain.tar.gz;mv avr8-gnu-toolchain-linux_x86_64 /usr/local/avr;rm avr-gcc-toolchain.tar.gz"
