name: 'Make sure all tests run & that fw can be built on pull-req'
run-name: ${{ github.actor }} initiated a pull request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - Dev

jobs:

  call_chk_devcontainer:
    name: Check valid devcontainer image
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/chk_devcontainer_img.yml
    with:
      image-id: iot-base-img:latest
    secrets:
      secr-token: ${{ secrets.GITHUB_TOKEN }}

  build_all_run_tests:
    name: Check all builds and tests
    runs-on: ubuntu-latest
    needs: call_chk_devcontainer
    permissions:
      contents: read
      pages: write
      id-token: write
    env:
      IMAGE_NAME: ${{ needs.call_chk_devcontainer.outputs.image-path }}

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Pull dev container
        run: docker pull ${IMAGE_NAME}

      - name: Run tests
        run: |
          docker run --rm \
            --mount type=bind,src=${{ github.workspace }},dst=/workspaces \
            --mount type=bind,src=$HOME,dst=/root \
            ${IMAGE_NAME} sh -c "cd /workspaces;./pipeline/config_build_run_test.sh"
            
      - name: Build target firmware
        run: |
          docker run --rm \
            --mount type=bind,src=${{ github.workspace }},dst=/workspaces \
            --mount type=bind,src=$HOME,dst=/root \
            ${IMAGE_NAME} sh -c "cd /workspaces;./pipeline/build_firmware_files.sh"
      
      - name: Update download files and timestamps
        run: |
          docker run --rm \
            --mount type=bind,src=${{ github.workspace }},dst=/workspaces \
            --mount type=bind,src=$HOME,dst=/root \
            ${IMAGE_NAME} sh -c "cd /workspaces;./pipeline/update_project_pages.sh"

   #   - name: Setup Pages
    #    uses: actions/configure-pages@v3

    #  - name: Upload artifact
     #   uses: actions/upload-pages-artifact@v1
     #   with:
          # Upload project pages
     #     path: './proj_pages/'

     # - name: Deploy to GitHub Pages
       # id: deployment
       # uses: actions/deploy-pages@v2
